#include <stdio.h>
#include <unistd.h>

int main()
{
  pid_t pid;
  printf("main program's Pid = %d\n", getpid());

  pid = fork();
  if (pid != 0)
    printf("A process (Pid = %d) has been generated by program (Pid %d) , from 1'st fork\n", pid, getpid());

  pid = fork();
  if (pid != 0)
    printf("A process (Pid = %d) has been generated by program (Pid %d) , from 2'nd fork\n", pid, getpid());

  pid = fork();
  if (pid != 0)
    printf("A process (Pid = %d) has been generated by program (Pid %d) , from 3'rd fork\n", pid, getpid());

  pid = fork();
  if (pid != 0)
    printf("A process (Pid = %d) has been generated by program (Pid %d) , from 4'th fork\n", pid, getpid());

  return 0;
}
